# Edge Device Configuration
device_id: "replay-edge-001"
backend_url: "http://localhost:8000"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 5000
  log_level: "INFO"

# Camera Discovery
camera:
  scan_subnet: "192.168.1.0/24"
  rtsp_timeout: 5
  discovery_interval: 30

# Recording Settings
recording:
  output_dir: "./recordings"
  max_file_size: "1GB"
  segment_duration: 300

# Backend Integration
backend:
  heartbeat_interval: 30
  upload_enabled: true
  api_key: "${API_KEY}"

# Storage Management
storage:
  max_disk_usage: 85
  cleanup_threshold: 90
  auto_cleanup: true